Script started on 2017年03月13日 (週一) 23時10分42秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m whoami;pe[Kwd
pd2vm
/home/pd2vm/lab1
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m git config -l
user.name=Chioupo
user.email=sos1991h@gmail.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/Chioupo/lab1.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m j[Kc[Kgit clone http://[K[K[K[Kps://github.com/Chioupo/k[Klab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m cat lab1.script
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m exit

Script done on 2017年03月13日 (週一) 23時12分00秒
